---
title: "R Notebook"
output: html_notebook
---
```{r}
install.packages('neuralnet')
```
```{r}
suppressWarnings(library(e1071))
suppressWarnings(library(caret))
```


```{r}
suppressWarnings(library(neuralnet))
```

```{r}
dataPath<-"./"
data <- read.csv(paste0(dataPath,"test_sample.csv"))
```
```{r}
set.seed(1)
nnDa2 <- neuralnet(class~.,
                   data=data,
                err.fct="ce",
                linear.output=FALSE,
                threshold=0.1,
                hidden = c(3))
```
```{r}
predict.nn <- predict(nnDa2, data[,1:2])
```
```{r}
conf_tuned <- table(data$class, predict.nn[, 1] > 0.5)
print('Base nn')
classAgreement(conf_tuned)$diag
```
```{r}
set.seed(1)
ctrl <- trainControl(method = "cv", number = 5)

nnFitOtto <- train(as.matrix(data[,1:2]),
                   data[,3], 
                   method = "nnet", 
                   trControl = ctrl,
                   tuneGrid=expand.grid(.size=3:10,.decay=.3))
nn.pred = predict(nnFitOtto,data[,1:2])
conf_nn <- table(data$class, nn.pred)
classAgreement(conf_nn)$diag
```
```{r}
summary(nnFitOtto)
```





